// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Cppcheck_VS_AddIn
{
    static class Vsix
    {
        public const string Id = "884bcde1-206c-4261-b159-b8df2942e457";
        public const string Name = "Cppcheck VS AddIn";
        public const string Description = @"Visual Studio integration for Cppcheck, an open-source static code analyzer for C++";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Vivian Lobo";
        public const string Tags = "cpp, cppcheck, code-analyzer, static-code-analyzer";
    }
}
