// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Cppcheck_VS_AddIn
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCppcheckCommandPackageString = "b9af5f5d-7b46-44d8-b37e-5e4e1d7fe93f";
        public const string guidCppcheckCommandPackageCmdSetString = "050e322e-8b72-4f90-90ab-7135ff965417";
        public const string guidImagesString = "8582c01b-ca87-4dad-b250-10515de95201";
        public static Guid guidCppcheckCommandPackage = new Guid(guidCppcheckCommandPackageString);
        public static Guid guidCppcheckCommandPackageCmdSet = new Guid(guidCppcheckCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CppcheckCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
